### ISSUE TITLE
Failed to instantiate one or more classes 

### ISSUE THREAD

**Issue by Th3CracKed** [hu2di/android-google-plus-one#1]
The following classes could not be instantiated:
- com.google.android.gms.plus.PlusOneButton
I tried to create a sample app my self and get this error than i searched for plusonebutton on github and i found your project and i download it , but same problem can you please help me ? 
Is there any tool that i should to download to resolve this problem?
`java.lang.NullPointerException
	at com.google.android.gms.plus.PlusOneDummyView$zzb.isValid(Unknown Source)
	at com.google.android.gms.plus.PlusOneDummyView.<init>(Unknown Source)
	at com.google.android.gms.plus.internal.zzm.zza(Unknown Source)
	at com.google.android.gms.plus.PlusOneButton.zzbk(Unknown Source)
	at com.google.android.gms.plus.PlusOneButton.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:475)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:262)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:220)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:186)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:334)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:345)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:245)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:368)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:567)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:549)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:549)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$1(RenderTask.java:680)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by hu2di** [comment]
Hi. Sorry for my late answer. But this app still works normally on my phone.
I have a few solutions for you:
- Check that your phone has google + installed
- Download again my project from Github, extract, open and run it without update any library,  compileSdkVersion, buildToolsVersion, classpath, googleplayservice...
Hope this help you,
Have a nice day!

**Comment by Th3CracKed** [comment]
Thanks for the answer
I have install google + 
I download your project + extract it 
When i import it i got this
<img width="350" alt="1" src="https://user-images.githubusercontent.com/10481816/31073771-92d7d99a-a76d-11e7-9867-930e92dbded4.PNG">
i choose No, the error disappear 
i got the same error com.google.android.gms.plus.PlusOneButton in the activity_main layout
<img width="449" alt="2" src="https://user-images.githubusercontent.com/10481816/31073787-ae5d5e74-a76d-11e7-8852-7543155d9ef6.PNG">
when i launch the app and select my google account i get this 
<img width="643" alt="3" src="https://user-images.githubusercontent.com/10481816/31073755-7f355890-a76d-11e7-972d-3d4e72e30513.PNG">
